### ISSUE TITLE
Port to tang nano 20K

### ISSUE THREAD

**Issue by naxeras** [nand2mario/mdtang#1]
¿It is possible a port for tang nano 20K?

Regards.

**Comment by siffland** [comment]
Or is it possible to port to the 25k.  Price point for the 25k is reasonable and it has a little more power than the 20k (The 25k may still may not be big enough though).  The price point for the 138k is entering the Mister Clone price range and a little harder to justify purchase, hopefully the 60k is cheaper when it comes out (please do not take this the wrong way, i am still very very grateful you are porting this to the 138k).

**Comment by nand2mario** [comment]
I am porting this to the 60k now. The 25k/20k needs more changes as the frame buffer needs rework. The 60k should be relatively straightforward.
